### ISSUE TITLE
Permission denied error in tif.filehandle.close() on Mac for a file in a network drive

### ISSUE THREAD

**Issue by AliShenasa** [cgohlke/tifffile#184] opened 2023-03-08 01:15 UTC
#### Description
On Mac, closing a TIFF file causes a permission denied error for files on a network drive. When the file is copied to the local machine there is no issue.
Mac Version: macOS Monterrey Version 12.6.1

#### Screenshots
![Error Message](https://i.imgur.com/Yxglml3.png)

#### Files
I am not sure how best to include the TIFF file, but I will gladly share it.

#### To Reproduce
```
with TiffFile('file_on_nas.tif') as tif:
    imagej_metadata = tif.imagej_metadata
```
or 
```
tif = TiffFile('file_on_nas.tif')
imagej_metadata = tif.imagej_metadata
tif.close()
```

**Comment by cgohlke** [comment] 2023-03-08 03:41
Strange. The file opens in read mode from a network drive but raises a permission error when closing? I can't reproduce this on Windows and could not find anything relevant by Google search.

Are there any warnings printed on the console? Can you run the code under `python -X dev`? 

Please share a file on Google drive or similar.

**Comment by AliShenasa** [comment] 2023-03-08 20:41
Heres how it looks using ```python -X dev```

![Main Program Error](https://i.imgur.com/9b8UHwR.png)

Here is the Tiff file:
https://drive.google.com/file/d/1ZH-oy2XpIErdD4NHEG5Cf-UXtNgI2UDv/view?usp=sharing

I made a short script just to test this error. Here it is:
```
import tifffile as tf
import tkinter as tk
from tkinter import filedialog


def loadFileName():
    root = tk.Tk()
    root.withdraw()
    root.attributes("-topmost", 1)

    trial_file_nm = filedialog.askopenfilename(title="Select files")
    return trial_file_nm

def open_tif(path):
	print(f"Opening {path}")

	with tf.TiffFile(path) as tif:
		print("tiff file was opened")

	print("tiff file was closed")


tiff_on_local = loadFileName()
tiff_on_nas = loadFileName()

open_tif(tiff_on_local)
open_tif(tiff_on_nas)
```

And here's the output:
![Error message](https://i.imgur.com/lYoWZDd.png)

Weirdly, on most runs it gives that same output, but on some runs it doesn't fail.
I hardcoded in the file names for this test script and now it works every time.

After I noticed that I ran my program several times and on a few it worked fine with the file from the network drive.

**Comment by cgohlke** [comment] 2023-03-09 20:07
Thanks for sharing the file. I can't find anything suspicious in it nor can I reproduce the issue. I'll add a `try...except` around the close statement for the next version of tifffile.

**Closed by cgohlke** 2023-03-09 20:07 UTC
