### ISSUE TITLE
can not parse positions from ome-tiff generated by micro-manager

### ISSUE THREAD

**Issue by bryantChhun** [cgohlke/tifffile#54] opened 2021-01-14 20:11 UTC
Following up on the discussion [at image.sc here](https://forum.image.sc/t/what-is-the-recommended-best-way-to-open-ome-tiffs-recorded-with-micromanger-1-and-2-from-python-3/47567), I'd like to provide a little more detail about what I see when trying to load the ome-tiffs:

if the dimensionality and folder structure is as such:
(T, P, Z, C, Y, X) = (50, 2, 5, 3, 2048, 2048)
![image](https://user-images.githubusercontent.com/25647712/104641801-18a0b800-565f-11eb-986e-f23c8241c26f.png)

The resulting array from running:
```
>>> a = tifffile.imread('/image_stack_tpzc_50tp_2p_5z_3c_2k_1_MMStack_2-Pos000_000.ome.tif')
>>> a.shape
>>> (50, 5, 3, 2048, 2048)
```

This is ok if it means that I can simply load the other series/positions and get a similar shape, however:
```
>>> b = tifffile.imread('/image_stack_tpzc_50tp_2p_5z_3c_2k_1_MMStack_2-Pos001_000.ome.tif')
>>> b.shape
>>> (510, 2048, 2048)
```
which is only a partial load of that series -- it should at least be (750, 2048, 2048)

From [pypi notes:](https://pypi.org/project/tifffile/)
> OME-TIFF stores up to 8-dimensional data in one or multiple TIFF of BigTIFF files.

So ideally we can get an array like (T, P, Z, C, Y, X) = (50, 2, 5, 3, 2048, 2048)

**Comment by cgohlke** [comment] 2021-01-14 22:50
> `a = tifffile.imread('/image_stack_tpzc_50tp_2p_5z_3c_2k_1_MMStack_2-Pos000_000.ome.tif')`
> `b = tifffile.imread('/image_stack_tpzc_50tp_2p_5z_3c_2k_1_MMStack_2-Pos001_000.ome.tif')`

I do not have access to those exact files and cannot comment on the partial loading issue.

> This is ok if it means that I can simply load the other series/positions

This is by design and agrees with how Bio-Formats imports those images into Fiji. Series may have different data types, shapes, etc and cannot in general be accessed as a single numpy or zarr array. Maybe in the future the OME-ZARR will handle these cases.

>> OME-TIFF stores up to 8-dimensional data in one or multiple TIFF of BigTIFF files.
> So ideally we can get an array like (T, P, Z, C, Y, X) = (50, 2, 5, 3, 2048, 2048)

OME does only support a very limited number, order, and kind of image dimensions. Position is not one of them. Hence positions are saved as separate series. 

Re `OME series: not an ome-tiff master file`:

This means the file does not contain the complete OME-XML metadata and tifffile is unable to find the master OME-TIFF file containing the complete metadata. Your OME-TIFF files created by MicroManager also contains a second `ImageDescription` tag with ImageJ metadata. Tifffile does not look for ImageJ metadata in the second `ImageDescription` tag in this case. This could be fixed.

**Comment by bryantChhun** [comment] 2021-01-14 23:14
>This means the file does not contain the complete OME-XML metadata and tifffile is unable to find the master OME-TIFF file containing the complete metadata. Your OME-TIFF files created by MicroManager also contains a second ImageDescription tag with ImageJ metadata. Tifffile does not look for ImageJ metadata in the second ImageDescription tag in this case. This could be fixed.

This might explain why ImageJ can identify the positions/scenes and allow them to be loaded.  In the meantime, is there a workaround to enable manual loading of the other series?
```
# this is the master OME-tiff
'/image_stack_tpzc_50tp_2p_5z_3c_2k_1_MMStack_2-Pos000_000.ome.tif'  

# this is the 2nd position/series whose metadata is in the above file
'/image_stack_tpzc_50tp_2p_5z_3c_2k_1_MMStack_2-Pos001_000.ome.tif'  
```

**Comment by cgohlke** [comment] 2021-01-15 19:12
I'm closing this. The numpy/zarr array shape for a particular series is correct. tifffile v2021.1.14 will fall back to ImageJ metadata (if any) if detecting series from OME-XML fails. The partial loading I cannot reproduce.

**Closed by cgohlke** 2021-01-15 19:12 UTC

**Comment by bryantChhun** [comment] 2021-01-15 19:23
Just a final note for any who encounter the same problem.  After opening a micro-manager ome-tiff in FIJI and seeing that positions are encoded as independent series, it seems the access mode should not be `imread` but instead:

```
with TiffFile("path to ome-tiff") as tif:
    pos0 = tif.asarray(series=0)
    pos1 = tif.asarray(series=1)
```

**Comment by cgohlke** [comment] 2021-01-15 20:15
Since you are interested in series, it's probably better to query the series interface:
```
with TiffFile('image_stack_tpzc_50tp_2p_5z_3c_512k_1_MMStack_2-Pos000_000.ome.tif') as tif:
    for series in tif.series:
        series.dtype
        series.shape
        series.axes
        data = series.asarray()
```
```
dtype('uint16')
(50, 5, 3, 256, 256)
'TZCYX'
dtype('uint16')
(50, 5, 3, 256, 256)
```
