### ISSUE TITLE
v2023.3.15 breaks reading of tiff file (ValueError: invalid entry in coordinates array)

### ISSUE THREAD

**Issue by joshua-gould** [cgohlke/tifffile#187] opened 2023-03-21 13:17 UTC
See attached tiff file downloaded from https://idr.openmicroscopy.org/webclient/?show=project-1504
[10X_c1-SBS-1_A1_Tile-102.sbs.tif.zip](https://github.com/cgohlke/tifffile/files/11028655/10X_c1-SBS-1_A1_Tile-102.sbs.tif.zip)

**Comment by cgohlke** [comment] 2023-03-21 15:41
Thanks for reporting. The issue is that the Micro-Manager metadata claims that this file is part of a `(3198, 1, 1, 5)` dataset and the workaround for the missing data fails in this case. That's going to be fixed in the next version. Try to specify `is_mmstack=False` as a workaround and fallback to OME-XML metadata.

Also, the file is missing the `_MMStack` and `.ome` in the filename, which are usual for Micro-Manager stacks..

**Closed by cgohlke** 2023-03-21 15:41 UTC

**Comment by cgohlke** [comment] 2023-03-21 23:40
Clearly, this file was renamed, breaking Micro-Manager and OME metadata.

**Comment by ziw-liu** [comment] 2023-04-07 17:35
The missing data is somewhat differentiable from the index map. [This](https://github.com/czbiohub/iohub/blob/c6329001535b9db2f965fc04d439232b240769fd/iohub/multipagetiff.py#L114-L131) is a workaround we used. Currently `tifffile==2023.3.21` will log a warning if a multi-file dataset is missing pages but still return the 'intended' shape with the missing chunks zero-filled in `asarray()` and `aszarr()`, and it would be useful if `tifffile` exposes those invalid indices (or the parsed index map) as an attribute. A synthetic incomplete dataset with missing files can be found [here](https://zenodo.org/record/6983916/preview/waveOrder_test_data.zip#tree_item581).

**Comment by cgohlke** [comment] 2023-04-07 23:32
> Currently tifffile==2023.3.21 will log a warning if a multi-file dataset is missing pages but still return the 'intended' shape with the missing chunks zero-filled 

Tifffile 2023.3.21 is actually trying to [squeeze missing data](https://github.com/cgohlke/tifffile/blob/fbe8976d8602b0a3ac7866a4271678a7f71e8f0a/tifffile/tifffile.py#L5838-L5856) from the MMStack. The OME parser does not squeeze.

I don't know if there is a right way to handle missing/corrupted data. It's up to Micro-Manager not to produce corrupted files and the user not to break up multi-file datasets.

**Comment by cgohlke** [comment] 2023-04-07 23:42
> it would be useful if tifffile exposes those invalid indices

Missing pages in a TiffPageSeries are either None or have an offset/bytecount of 0.

**Comment by ziw-liu** [comment] 2023-04-10 18:01
> Tifffile 2023.3.21 is actually trying to [squeeze missing data](https://github.com/cgohlke/tifffile/blob/fbe8976d8602b0a3ac7866a4271678a7f71e8f0a/tifffile/tifffile.py#L5838-L5856) from the MMStack. The OME parser does not squeeze.

Is it only shrinking single-file datasets? The `multifile` flag bypasses the shrinkage:
https://github.com/cgohlke/tifffile/blob/fbe8976d8602b0a3ac7866a4271678a7f71e8f0a/tifffile/tifffile.py#L5836-L5837

For example it does not shrink the shape representing the entirely missing files in the truncated test dataset I posted. Also, even shape shrinking works, some missing pages may still remain because the truncation may not be aligned in each dimension.

> I don't know if there is a right way to handle missing/corrupted data. It's up to Micro-Manager not to produce corrupted files and the user not to break up multi-file datasets.

I think it makes sense either to shrink or not to shrink the missing pages. But we need some way to tell the downstream analysis that these are missing without having to check if all the values in the returned array is zero. The corrupted files is not just a result of MM not shutting down gracefully, but also can be due to inevitable events in acquisitions (e.g. microscope failed).

> Missing pages in a TiffPageSeries are either None or have an [offset/bytecount of 0](https://github.com/cgohlke/tifffile/blob/fbe8976d8602b0a3ac7866a4271678a7f71e8f0a/tifffile/tifffile.py#L5782-L5784).

That's exactly what we need! Knowing which indices are missing from the returned array will be very helpful.

**Comment by cgohlke** [comment] 2023-04-10 19:07
> Is it only shrinking single-file datasets?

Tifffile only shrinks datasets if the indexmap does not have enough entries for the dataset shape and no other files belonging to the dataset are found. That is the case when single files are taken out of a multi-file dataset. Tifffile does not distinguish between, e.g., single/few files missing from a multi-file dataset and a valid, sparse acquisition. I.e., datasets with two or more existing files are not squeezed.

> Knowing which indices are missing from the returned array will be very helpful.

AFAIK, numpy and zarr arrays can not provide that information and MMStack datasets can be sparse on purpose.

**Comment by ziw-liu** [comment] 2023-04-10 20:21
> AFAIK, numpy and zarr arrays can not provide that information and MMStack datasets can be sparse on purpose.

I think filing arrays with zeros as they are now is a good solution, and we also have intentionally sparse MM datasets. In fact, knowing which pages are intentionally missing can be useful for these datasets too. I think both of these conditions can be represented by a `TiffSeries` state that records the filling operation. For now this information is aggregated (counted), logged as a warning, and then discarded after the series parsing function returns. And it will be nice to have it accessible from a attribute of the series object, for example in the form of a binary index mask. If this is too eager for larger datasets, it can also be a missing index list or a lazily resolved query (equivalent of `bool(np.size==0)` if it was not filled) per plane.

**Comment by cgohlke** [comment] 2023-04-10 23:33
> I think filing arrays with zeros as they are now is a good solution

Missing data in Zarr arrays have a value of `fillvalue`, which is zero by default. In numpy arrays, zero is currently hardcoded to allow for overcommitting of memory.

> In fact, knowing which pages are intentionally missing can be useful for these datasets too

Is that actually possible for MMStack or am I confusing it with the new NDTiff format? Anyway, handling sparse structures, ragged arrays, tiled frames, and overlapping tiles are out of the scope of tifffile (and numpy, and Zarr, and TIFF spec). 

> For now this information is aggregated (counted), logged as a warning, and then discarded after the series parsing function returns. And it will be nice to have it accessible from a attribute of the series object, for example in the form of a binary index mask. If this is too eager for larger datasets, it can also be a missing index list or a lazily resolved query

Not sure I follow. The information of which data is missing is available in the items of the TiffPageSeries as mentioned earlier. A "binary index mask" can be obtained by comparing the zarr array to `fillvalue` or from that information and the shapes of the series (re numpy.unravel_index; although that would not generally be correct for all kind of TIFF files).

**Comment by ziw-liu** [comment] 2023-04-11 00:50
> Is that actually possible for MMStack or am I confusing it with the new NDTiff format?

Micro-Manager can acquire Z-stack (3D) data for some channels and only one slice (2D) for some other channels in a single acquisition -- the 'Z-stack' check box for each channel can be toggled separately. And these files can be opened in ImageJ via the MM plugin (with the not acquired pages being zero-filled).

From my understanding, the 'missing' pages here are not really breaking the TIFF spec, because every page written will have valid data and point to the next page as it would normally do. It is the 'intended dimension' field in the Micro-Manager metadata that is lacking expressiveness, and is compensated by a `0` offset in the index map. Since the index map is already parsed and the `0` indices are already counted, downstream applications does not have to duplicate the computation if `tifffile` can expose such information.

> Anyway, handling sparse structures, ragged arrays, tiled frames, and overlapping tiles are out of the scope of tifffile (and numpy, and Zarr, and TIFF spec).

NumPy and TIFF does not support sparse data, but chunk-level sparsity is explicitly supported in Zarr. The default behavior after zarr-python 2.11 is to not write the empty chunks. This is exactly the 'sparse' data structure we have with these 'sparse' TIFF series, since in `ZarrTiffStore` the chunk size is a TIFF page. In zarr-python `DirectoryStore`, a collection of the keys to all the initialized chunks (in MMStack that would be written TIFF pages) can be accessed by inspecting the keys of the `chunk_store`. IMO a way to know which chunks are not initialized makes `ZarrTiffStore` a more complete implementation. Do you think if it's possible to expose an API to check if a chunk (page) is written in `ZarrTiffStore`? Or even nicer, a `ZarrTiffStore` or `TiffPageSeries` 'get chunk/page' method that returns a NumPy array based on (R, T, C, Z) index if it exists, and `None` or an empty NumPy array (`szie==0`) if it doen't.

> A "binary index mask" can be obtained by comparing the zarr array to `fillvalue` or from that information and the shapes of the series

This will work, yet at the cost of having to zero-fill all the NumPy arrays in memory. And they can be quite a lot of mallocs if this happens for many pages.

**Comment by cgohlke** [comment] 2023-04-11 02:16
> Micro-Manager can acquire Z-stack (3D) data for some channels and only one slice (2D) for some other channels in a single acquisition -- the 'Z-stack' check box for each channel can be toggled separately.

Thanks for confirming.

> It is the 'intended dimension' field in the Micro-Manager metadata that is lacking expressiveness, and is compensated by a 0 offset in the index map. Since the index map is already parsed and the 0 indices are already counted, downstream applications does not have to duplicate the computation if tifffile can expose such information.

That is fundamental to tifffile, which provides access to decoded image data (in form of numpy or zarr arrays) and metadata (mostly in form of built-in Python types) but does not curate metadata to further describe the image arrays.  It has long been planned to add xarray attributes to various tifffile classes, but that is a significant task, which would require multi-month funding. I'm not sure that xarray can help identifying missing data in this case.

> The default behavior after zarr-python 2.11 is to not write the empty chunks.

The current implementation of ZarrTiffStore precedes zarr-python 2.11. It might be as easy as returning a size-zero array from `ZarrStore._empty_chunk`. I'll look into that.

> a ZarrTiffStore or TiffPageSeries 'get chunk/page' method that returns a NumPy array based on (R, T, C, Z) index if it exists, and None or an empty NumPy array (szie==0) if it doen't.

Just calculate the linear index in the series with `numpy.unravel_index` and check if the item is None or has a zero offset.

**Comment by cgohlke** [comment] 2023-04-11 03:19
>  In zarr-python DirectoryStore, a collection of the keys to all the initialized chunks (in MMStack that would be written TIFF pages) can be accessed by inspecting the keys of the chunk_store

Can you provide example code?

**Comment by ziw-liu** [comment] 2023-04-11 16:08
> Can you provide example code?

Found this [here](https://github.com/zarr-developers/zarr-python/issues/587#issuecomment-680705562). Source code [here](https://github.com/zarr-developers/zarr-python/blob/4b0705c6d85cdfc20a33cbb39a90c8c9d11006c1/zarr/storage.py#L1153-L1155).

Also just found that Zarr has [some support](https://zarr.readthedocs.io/en/stable/tutorial.html#ragged-arrays) for ragged arrays too.
