### ISSUE TITLE
Backwards compatibility issue with tile writing

### ISSUE THREAD

**Issue by illWill** [cgohlke/tifffile#239] opened 2024-02-02 14:13 UTC
I encountered a slightly confusing backwards compatibility issue related to tifffile writing of tiled layers (I am attempting to 'spoof' svs files).  I was previously writing lists of tiles, but I find now that this does not work properly as the "shape" checker recognizes that the list is not an iterable, and tries to check its shape.

The following code:

```
        tif.write(
            down4x,
            tile=(256, 256),
            shape=(math.ceil(rows/4)*256,math.ceil(columns/4)*256,3),
            description="Aperio Leica Biosystems GT450 v1.0.1 \n{0}x{1} [0,0,{0}x{1}] JPEG/YCC Q=91|AppMag = 40|Date = 10/14/2022|Exposure Scale = 0.000001|Exposure Time = 8|Filtered = 3|Focus Offset = -0.500000|Gamma = 2.2|Left = 16.640453338623|MPP = {2}|Rack = 1|ScanScope ID = SS12046|Slide = 1|StripeWidth = 4096|Time = 14:46:05|Time Zone = GMT-0400|Top = 30.810459136963".format(int(corr.TotalPixelMatrixColumns/4),int(corr.TotalPixelMatrixRows/4),mpp*4),
            subfiletype=1,
            #resolution=(1e4 / pixelsize, 1e4 / pixelsize),
            #metadata=metadata,
            **options
        )
```

where down4x is a list of nparray tiles, was broken, but fixed when wrapped in an iter:

```
        tif.write(
            iter(down4x),
            tile=(256, 256),
            shape=(math.ceil(rows/4)*256,math.ceil(columns/4)*256,3),
            description="Aperio Leica Biosystems GT450 v1.0.1 \n{0}x{1} [0,0,{0}x{1}] JPEG/YCC Q=91|AppMag = 40|Date = 10/14/2022|Exposure Scale = 0.000001|Exposure Time = 8|Filtered = 3|Focus Offset = -0.500000|Gamma = 2.2|Left = 16.640453338623|MPP = {2}|Rack = 1|ScanScope ID = SS12046|Slide = 1|StripeWidth = 4096|Time = 14:46:05|Time Zone = GMT-0400|Top = 30.810459136963".format(int(corr.TotalPixelMatrixColumns/4),int(corr.TotalPixelMatrixRows/4),mpp*4),
            subfiletype=1,
            #resolution=(1e4 / pixelsize, 1e4 / pixelsize),
            #metadata=metadata,
            **options
        )
```

I am guessing that this does not affect many people, but this unexpectedly broke my code when I transferred it to a machine that had a more current tifffile version and was initially really puzzling. Not sure if this should be either documented more explicitly or if the code of the shape checker should be made somewhat more complex to test this circumstance.

Thank you for this software. I am a bit new at opening github issues

**Comment by cgohlke** [comment] 2024-02-02 16:20
That change was made deliberately in 2022.5.4:

https://github.com/cgohlke/tifffile/blob/00a3c6a7b7adfc886cb1e59e423d13612b376d68/CHANGES.rst?plain=1#L192

The change was necessary for efficiency, to support iterators of strips and raw segments, and clean up typing and documentation. This should have been marked as breaking, but probably the tests passed without changes so the breakage went unnoticed. I think the current state works as intended and documented. Let me know if not. I do not intend to support writing list/tuple of tiles.

**Closed** 2024-02-12 16:33 UTC
