### ISSUE TITLE
TIF have 3 layers then 3 PNG export form TIFF

### ISSUE THREAD

**Issue by kmanimurugan** [cgohlke/tifffile#226] opened 2023-09-19 05:18 UTC
Can you please provide sample code to extract the TIFF layers to different PNG files
If TIF have 3 layers then 3 PNG export form TIFF

**Comment by cgohlke** [comment] 2023-09-19 05:24
Duplicate of https://github.com/cgohlke/psdtags/issues/8

**Closed** 2023-09-19 05:24 UTC

**Comment by kmanimurugan** [comment] 2023-09-19 05:27
@cgohlke 
I got error when i tried that

for layer in isd.layers:
print(layer.name)
tifffile.imshow(layer.asarray(), title=layer.name)
# mask = layer.mask
# print(mask)
# imwrite('_test.jp2', layer.channel)
# # Image.fromarray(layer.mask).save('%s.png' % layer.name)
for channel in layer.channels:
ch = channel.data # a numpy array
imagecodecs.imwrite(layer.name + f'{channel.channelid}.png', channel.data)

    Tried the above and got error
    Traceback (most recent call last):
File "/Users/manimurugank/Projects/Python/plusImageDownload/pulseTifImage.py", line 45, in
imagecodecs.imwrite(layer.name + f'{channel.channelid}.png', channel.data)
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/imagecodecs/imagecodecs.py", line 1516, in imwrite
image: bytes = codec(data, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "imagecodecs/_png.pyx", line 156, in imagecodecs._png.png_encode
ValueError: invalid data shape, strides, or dtype
